import { ProfileImageWithName } from '@/components/molecules/ProfileImageWithName'
import { MainWithHeaderAndFooter } from '@/components/templates/MainWithHeaderAndFooter'

import type { NextPageWithLayout } from '@/types/app'

const Home: NextPageWithLayout = () => (
  <div>
    HOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOMEHOME
    HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME
    HOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME
    HOME HOME HOME HOMEHOMEHOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME
    HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME HOME HOME HOME HOME
    HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOMEHOME HOME HOME HOME HOME HOME
    <ProfileImageWithName pageComment="ポートフォリオ" />
  </div>
)

Home.getLayout = page => <MainWithHeaderAndFooter pageName="Home">{page}</MainWithHeaderAndFooter>

export default Home
